name: Push new tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  push-scan:
    uses: mconf/mconf-ci-jobs/.github/workflows/all-build-push-scan-harbor.yml@main
    secrets: inherit
    with:
      runs-on: '["ubuntu-22.04"]'
      image_name: aws-batch-exporter
      organization: ops
      trivy-scanners: "vuln,config"
